import { portfolioSchema } from './fixtures/portfolio-schema.mjs';
import { PGlite } from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
const owner='00000000-0000-4000-8000-000000000001';
const row=(id,price=100)=>({id:`00000000-0000-4000-8000-${String(id).padStart(12,'0')}`,user_id:owner,symbol:'QA',name:'QA',transaction_type:'buy',trade_date:'2026-01-01',quantity:1,price,fee:0,currency:'KRW',fx_rate_to_krw:1,usd_krw_rate_at_transaction:1300,created_at:'2026-01-01T00:00:00Z'});
test('Postgres migration: atomic replacement, CAS, idempotency, RLS, stale performance write',async()=> {
 const db=new PGlite();
 await db.exec(portfolioSchema(owner));
 for(const table of ['portfolio_transactions','portfolio_preferences','portfolio_snapshots']) await db.exec(`alter table public.${table} enable row level security; create policy own on public.${table} for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id); grant select,insert,update,delete on public.${table} to authenticated;`);
 await db.query('insert into public.portfolio_transactions select * from jsonb_populate_recordset(null::public.portfolio_transactions,$1)',[JSON.stringify([row(99)])]);
 await db.exec(readFileSync('supabase/migrations/20260905225656_atomic_portfolio_ledger.sql','utf8'));
 assert.equal((await db.query('select count(*)::int n from centifolio_release_backup.portfolio_transactions')).rows[0].n,1);
 for(const role of ['anon','authenticated','service_role']) assert.equal((await db.query("select has_schema_privilege($1,'centifolio_release_backup','usage') allowed",[role])).rows[0].allowed,false);
 await db.exec(`set role authenticated; set request.jwt.claim.sub='${owner}';`);
 await assert.rejects(db.query('select * from centifolio_release_backup.portfolio_transactions'),/permission denied/);
 const read=async()=> (await db.query('select public.read_portfolio_ledger() snapshot')).rows[0].snapshot;
 const commit=async(revision,id,rows)=>(await db.query('select public.commit_portfolio_ledger($1,$2,$3) snapshot',[revision,`10000000-0000-4000-8000-${String(id).padStart(12,'0')}`,JSON.stringify(rows)])).rows[0].snapshot;
 const empty=await read();const first=await commit(empty.revision,1,[row(10),row(11)]);
 await assert.rejects(commit(empty.revision,2,[row(12)]),/changed/);
 await assert.rejects(commit(first.revision,3,[row(12,-1)]),/Invalid/);
 assert.deepEqual(await read(),first);
 const replaced=await commit(first.revision,4,[row(12)]);assert.equal(replaced.transactions.length,1);
 assert.deepEqual(await commit(first.revision,4,[row(12)]),replaced);
 await assert.rejects(commit(replaced.revision,4,[row(13)]),/reused/);
 await assert.rejects(commit(replaced.revision,5,[{...row(14),user_id:'00000000-0000-4000-8000-000000000002'}]),/Invalid/);
 await assert.rejects(db.query('select public.save_portfolio_performance($1,$2,$3)',[first.revision,'2026-01-01','[]']),/changed/);
 await db.query('select public.save_portfolio_performance($1,$2,$3)',[replaced.revision,'2026-01-01','[]']);
 const ordered=await commit(replaced.revision,6,[row(19),row(15)]);assert.deepEqual(ordered.transactions.map(t=>t.id),[row(19).id,row(15).id]);
 await assert.rejects(commit(ordered.revision,7,[{...row(20),fx_rate_to_krw:-1}]),/Invalid/);assert.deepEqual(await read(),ordered);
 const point={date:'2026-01-01',cutoffAt:'2026-01-01T14:59:59Z',assetValueKRW:200,twrIndex:100,netFlowKRW:0,cumulativeNetFlowKRW:200,cumulativeProfitKRW:0,active:true,final:true};
 await db.query('select public.save_portfolio_performance($1,$2,$3)',[ordered.revision,'2026-01-01',JSON.stringify([point])]);
 await assert.rejects(db.query('select public.save_portfolio_performance($1,$2,$3)',[ordered.revision,'2026-01-01',JSON.stringify([{...point,assetValueKRW:300},{...point,date:'2026-01-02',assetValueKRW:-1}])]));
 assert.equal(Number((await db.query('select total_assets_krw from public.portfolio_snapshots')).rows[0].total_assets_krw),200);
 await db.exec(`set request.jwt.claim.sub='00000000-0000-4000-8000-000000000002'`);assert.equal((await read()).transactions.length,0);
 await db.exec('reset role;');
 await db.exec(readFileSync('supabase/tests/atomic-ledger-smoke.sql','utf8'));
 await db.exec(readFileSync('supabase/rollback/atomic_portfolio_ledger.sql','utf8'));
 assert.equal((await db.query('select count(*)::int n from centifolio_release_backup.portfolio_transactions')).rows[0].n,1,'rollback preserves the recovery copy');
 assert.equal((await db.query('select count(*)::int count from portfolio_transactions')).rows[0].count,2);
 assert.equal((await db.query("select count(*)::int count from information_schema.columns where table_name='portfolio_transactions' and column_name='ledger_position'")).rows[0].count,0);
 await db.close();
});
